spring.application.name=springboot-industry-practice

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5433/springboot_industry_practice
spring.datasource.username=postgres
spring.datasource.password=root

#spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml


spring.data.redis.host=localhost
spring.data.redis.port=6379