CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255)     NOT NULL,
    description VARCHAR(255),
    price       DOUBLE PRECISION NOT NULL,
    category_id BIGINT           NOT NULL,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES categories (id)
);